-- Run this script in your Supabase SQL Editor to create the required tables.

-- 1. Create the Raw Usage Table (Source)
CREATE TABLE IF NOT EXISTS public.raw_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    data_added TIMESTAMPTZ DEFAULT NOW(),
    temperature FLOAT,
    soil_moisture FLOAT,
    nitrogen FLOAT
);

-- 2. Create the Cleaned Data Table (Destination)
CREATE TABLE IF NOT EXISTS public.cleaned_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    data_added TIMESTAMPTZ,
    
    -- Raw Values (kept for reference)
    temperature FLOAT,
    soil_moisture FLOAT,
    nitrogen FLOAT,
    
    -- Cleaned/Imputed Values
    cleaned_temperature FLOAT,
    cleaned_soil_moisture FLOAT,
    cleaned_nitrogen FLOAT,
    
    -- Quality Assessment Metrics
    temperature_qv FLOAT,
    temperature_status TEXT,
    soil_moisture_qv FLOAT,
    soil_moisture_status TEXT,
    nitrogen_qv FLOAT,
    nitrogen_status TEXT
);

-- User already has 'predictions' table created manually.
-- Schema Reference:
-- CREATE TABLE IF NOT EXISTS predictions (
--     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     device_id INT,
--     created_at TIMESTAMPTZ DEFAULT NOW(), 
--     forecast_time TIMESTAMPTZ,            
--     temperature FLOAT8,
--     soil_moisture FLOAT8,
--     nitrogen FLOAT8
-- );

-- 4. Create the Recommendations Table (Actionable Insights)
CREATE TABLE IF NOT EXISTS public.recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    
    category TEXT,   -- 'Critical', 'Warning', 'Action', 'Info'
    parameter TEXT,  -- 'Moisture', 'Nitrogen', 'Weather'
    message TEXT,
    priority INT     -- 1 (Highest) to 5 (Lowest)
);

-- Optional: Enable RLS (Row Level Security) if you need it, 
-- otherwise these tables are public if your project settings allow it (or internal use only via service_role key).
-- ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.cleaned_data ENABLE ROW LEVEL SECURITY;
