-- Observations Table Setup
-- Run this script in your Supabase SQL Editor to create the observations table

CREATE TABLE IF NOT EXISTS public.observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plot_id TEXT NOT NULL,
    author TEXT NOT NULL,
    note TEXT NOT NULL,
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add an index on plot_id for faster queries
CREATE INDEX IF NOT EXISTS idx_observations_plot_id ON public.observations(plot_id);

-- Add an index on date for chronological sorting
CREATE INDEX IF NOT EXISTS idx_observations_date ON public.observations(date DESC);

-- Optional: Add a foreign key constraint if you have a plots table
-- ALTER TABLE public.observations 
-- ADD CONSTRAINT fk_observations_plot 
-- FOREIGN KEY (plot_id) REFERENCES public.plots(id) ON DELETE CASCADE;

-- Enable Row Level Security (optional, configure based on your auth needs)
-- ALTER TABLE public.observations ENABLE ROW LEVEL SECURITY;

-- Example: Create a policy for authenticated users to read all observations
-- CREATE POLICY "Users can view all observations"
--     ON public.observations
--     FOR SELECT
--     TO authenticated
--     USING (true);

-- Example: Create a policy for authenticated users to insert observations
-- CREATE POLICY "Users can create observations"
--     ON public.observations
--     FOR INSERT
--     TO authenticated
--     WITH CHECK (true);

COMMENT ON TABLE public.observations IS 'Stores field observations and notes for plots';
COMMENT ON COLUMN public.observations.plot_id IS 'Reference to the plot being observed';
COMMENT ON COLUMN public.observations.author IS 'Name or identifier of the person making the observation';
COMMENT ON COLUMN public.observations.note IS 'The observation content/description';
COMMENT ON COLUMN public.observations.date IS 'When the observation was made (can be backdated)';
