"""
Unit Tests for Module 4: Decision Support System (DSS)
Refactored to match Test Case Documentation (TC16, TC17, etc.)
Continuing from Module 2 (TC10-TC15)
"""

import pytest
import pandas as pd
from datetime import datetime, timedelta

class TestDecisionSupportSystem:
    """Test Suite for Recommendation Engine - Module 4"""

    # ============================================================
    # RAIN RULE TESTS (RULE 1)
    # ============================================================

    def test_TC16_rain_clear_skies(self):
        """TC16: Verify 'Clear Skies' message when rain is below threshold (<1mm)."""
        rain_val = 0.5
        # Threshold logic check
        is_clear = rain_val < 1.0 # Using 1.0 as CLEAR_SKIES_THRESHOLD
        assert is_clear is True

    def test_TC17_rain_warning(self):
        """TC17: Verify fertilization task is rescheduled during moderate rain (5mm)."""
        rain_val = 5.0
        # Logic: If rain > 1mm and task is fertilization -> RESCHEDULE
        action = "STAY"
        if rain_val > 1.0:
            action = "RESCHEDULE"
        assert action == "RESCHEDULE"

    def test_TC18_heavy_rain(self):
        """TC18: Verify heavy rain (>10mm) triggers an erosion/inspection alert."""
        rain_val = 12.0
        alert_triggered = False
        if rain_val > 10.0: # HEAVY_RAIN_THRESHOLD
            alert_triggered = True
        assert alert_triggered is True

    # ============================================================
    # MOISTURE RULE TESTS (RULE 2)
    # ============================================================

    def test_TC19_moisture_dry_soil(self):
        """TC19: Verify irrigation alert triggers when moisture is below 15%."""
        moisture = 12.0
        needs_irrigation = moisture < 15.0 # DRY_SOIL_THRESHOLD
        assert needs_irrigation is True

    def test_TC20_moisture_waterlogging(self):
        """TC20: Verify waterlogging alert triggers when moisture exceeds 25%."""
        moisture = 28.0
        waterlog_risk = moisture > 25.0 # WATERLOGGING_THRESHOLD
        assert waterlog_risk is True

    # ============================================================
    # TEMPERATURE RULE TESTS (RULE 3)
    # ============================================================

    def test_TC21_temp_cold_stress(self):
        """TC21: Verify cold stress alert when temperature drops below 20°C."""
        temp = 18.0
        growth_retardation = temp < 20.0 # COLD_STRESS_THRESHOLD
        assert growth_retardation is True

    def test_TC22_temp_heat_stress_shift(self):
        """TC22: Verify heat stress (>35°C) suggests shifting tasks to morning/evening."""
        temp = 37.0
        suggested_action = "NONE"
        if temp > 35.0: # HEAT_STRESS_THRESHOLD
            suggested_action = "TIME_SHIFT"
        assert suggested_action == "TIME_SHIFT"

    # ============================================================
    # SENSOR HEALTH TESTS
    # ============================================================

    def test_TC23_sensor_health_alert_format(self):
        """TC23: Verify sensor alert is triggered when readings are out of threshold for >24 hours."""
        # Simulated sensor data
        current_moisture = 105.0  # Out of threshold (normal: 1-100%)
        threshold_min = 1.0
        threshold_max = 100.0
        duration_hours = 28.5  # More than 24 hours
        
        # Check if sensor is out of threshold
        is_out_of_range = (current_moisture < threshold_min) or (current_moisture > threshold_max)
        
        # Check if duration exceeds 24 hours
        is_prolonged = duration_hours > 24.0
        
        # Alert should be triggered when both conditions are met
        should_alert = is_out_of_range and is_prolonged
        assert should_alert is True, "Alert should trigger when sensor is out of range for >24h"
        
        # Verify alert message format (as would be generated by the system)
        alert_reason = f"⚠️ Sensor Alert: Moisture readings out of normal range ({threshold_min}-{threshold_max}%) for {duration_hours}+ hours. Current: {current_moisture}%. Sensor may be broken or lost connectivity. Check hardware."
        
        # Verify message contains key information
        assert "out of" in alert_reason.lower(), "Alert should mention 'out of range'"
        assert str(duration_hours) in alert_reason, "Alert should include duration"
        assert str(current_moisture) in alert_reason, "Alert should include current value"
        assert "hardware" in alert_reason.lower() or "connectivity" in alert_reason.lower(), \
               "Alert should suggest checking hardware or connectivity"


# ============================================================
# Run Tests
# ============================================================
if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
